language: csharp
solution: EMS.sln
mono: none
dotnet: 2.1.302

jobs:
  include:
    - stage: test EF
      script:
        - dotnet restore
        - dotnet build
        - dotnet test test/EMS.DataSources.EntityFramework.Tests/EMS.DataSources.EntityFramework.Tests.csproj

script:
  - dotnet restore
  - dotnet build


