language: csharp
solution: EMS.sln
mono: none
dotnet: 2.1.302

jobs:
  include:
    - stage: test EfDataContext
      script:
        - dotnet restore
        - dotnet build
        - dotnet test test/EMS.DataSources.EntityFramework.Tests/EMS.DataSources.EntityFramework.Tests.csproj
    - stage: test Translator
      script:
      - dotnet restore
      - dotnet build
      - dotnet test test/EMS.Translator.Tests/EMS.Translator.Tests.csproj

script:
  - dotnet restore
  - dotnet build


